  - name: Create Directory for mount
    become: true
    ansible.builtin.file:
      path: /mnt/SOB_Certificate
      recurse: true
      state: directory
      mode: 0775
      owner: oracle
      group: oinstall

  - name: Insert a line at the end of a file.
    lineinfile:
      path: /etc/fstab
      line:  //GEZVWCARP001\SOB-Certificate$/SOB-Certificate$ /mnt/SOB_Certificate cifs credentials=
    become: true