

  - name: resize volume groupe to max 
    become: true
    community.general.lvg:
      vg: "{{ vg_name }}"
      pvs: "{{ pvs_name }}"
      pvresize: yes

  - name: resize logical volume 
    become: true
    community.general.lvol:
      vg: "{{ vg_name }}"
      lv: "{{ lv_name }}"
      size: "{{ lv_size }}"
      resizefs: yes