  - name: Copy lc binary installation to /tmp
    copy:
      src: /home/alexcinicher.edi/ansible/roles/lc/files/hcp_linux_x64_release_4.23.0
      dest: /tmp/hcp_linux_x64_release_4.23.0
    when: already_running.rc == 1

  - name: Copy lc install script to /tmp
    copy:
      src: /home/alexcinicher.edi/ansible/roles/lc/files/lc_linux_installer.sh
      dest: /tmp/lc_linux_installer.sh
    when: already_running.rc == 1
 


  

   