  - name: install apache 
    apt: 
      name: apache2
      state: latest
    become: true 


  - name: enable apache 
    service:
      name: apache2
      enabled: yes
    become: true

  - name: enshure apache is running 
    ansible.builtin.service:
      name: apache2
      state: started
    become: true 


  