  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Print the package facts
    ansible.builtin.debug:
      var: ansible_facts.packages['samba']


  - name: Ensure Samba-related packages are installed.
    package: "name={{ item }} state=installed"
    with_items:
      - samba
      - samba-client
      - samba-common
      - cifs-utils
    when: "'samba' not in ansible_facts.packages"
    become: true 



  - name: enable smb service 
    service:
      name: smb.service
      enabled: yes
    become: true    
    
  - name: enable nmb service
    service:
      name: nmb.service
      enabled: yes
    become: true

  
