- name: Create a new database
  mysql_db:
    name: "{{ db1_name }}"
    state: present
    login_host: localhost
    login_port: 3306
    login_user: "{{ mysql_root }}"
    login_password: "{{ mysql_root_pass }}"
  
 
- name: Create user and grant privileges for database
  mysql_user:
    name: "{{ dbuser1_name }}"
    host: "{{ ansible_hostname }}"
    password: "{{ dbuser1_pass }}"
    priv: '{{ dbuser1_name  }}.*:ALL'
    state: present
    login_host: localhost
    login_port: 3306
    login_user: "{{ mysql_root }}"
    login_password: "{{ mysql_root_pass }}"