- name: remove old git
  package: 
    name: git
    state: absent

- name: add IUS centos 7 repo 
  package: 
    name: https://centos7.iuscommunity.org/ius-release.rpm 
    state: installed 
  

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

#- name: install git and addons 
  #package: 
    #name: "{{ item }}"
    #state: installed
  #with_items: git2u-all , wget 

- name: install addons to git  
  package: 
    name: "{{ item }}"
    state: installed
  with_items: perl-CPAN , gettext-devel , perl-devel , openssl-devel , zlib-devel

