  - name: Gathering service facts
    service_facts:
    register: services_state
  - debug: var=services_state.ansible_facts.services["mdatp.service"].state
  

  - name: enshure mdatp is running 
    ansible.builtin.service:
      name: mdatp.service
      state: started
    become: true
    when: ansible_facts.services["mdatp.service"].state  == "stopped" or 
          ansible_facts.services["mdatp.service"].state  == "inactive" or
          ansible_facts.services["mdatp.service"].state  == "unknown"
 

  - name: update defender definitions
    become: true
    command: mdatp definitions updates