- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://yum.mariadb.org/10.1/centos7-amd64"
    gpgkey: "https://yum.mariadb.org/RPM-GPG-KEY-MariaDB"
    gpgcheck: true 


- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: MariaDB-server , MariaDB-client , MySQL-python
  ignore_errors: yes
 
  

- name: ensuhre service is ruuning
  service:
    name: 'mariadb'
    state: 'restarted'
  
- name: delete anonymous MySQL server user
  action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"

- name: remove the MySQL test database
  action: mysql_db db=test state=absent
  

- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password='{{ mysql_root_pass }}'
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    


- name: setup semaphore database
  mysql_db:
    name: "{{ semaphore_mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    login_host: "{{ semaphore_mysql_host }}"
    login_port: "{{ semaphore_mysql_port }}"
  

- name: setup semaphore database user
  mysql_user:
    name: "{{ semaphore_mysql_user }}"
    host: "{{ semaphore_mysql_allowed_host }}"
    password: "{{ semaphore_mysql_password }}"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    login_host: "{{ semaphore_mysql_host }}"
    login_port: "{{ semaphore_mysql_port }}"
    priv: "{{ semaphore_mysql_db }}.*:ALL,GRANT"
  when: semaphore_mysql_create_db
 