 - name: Download foo.conf
   get_url:
     url: https://github.com/ansible-semaphore/semaphore/releases/download/v2.5.1/semaphore_2.5.1_linux_amd64.rpm
     dest: /root/semaphore_2.5.1_linux_amd64.rpm
     mode: '0777'

 - name: Install package.
   yum:
     name: /root/semaphore_2.5.1_linux_amd64.rpm
     state: present