  - name: Create MDATP directories
    become: true
    ansible.builtin.file:
      path: /etc/opt/microsoft
      state: directory
      recurse: yes
      mode: 0775
      owner: root
      group: root
     

  - name: Create MDATP directories 2
    become: true
    ansible.builtin.file:
      path: /etc/opt/microsoft/mdatp
      state: directory
      recurse: yes
      mode: 0775
      owner: root
      group: root
