

  - name: add first repos for ad connect 
    ansible.builtin.apt_repository:
      repo: deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
      state: present
    become: true 



  - name: Set FQDN as a hostname 
    ansible.builtin.hostname:
      name: "{{hostname}}.corp.zim.com" 
    become: true


  - name: install pexpect
    pip:
      name: pexpect
    become: yes


  - name: Install requierd packages for ad connect 
    apt:
      name: "{{ item }}"
      state: latest
    become: true
    with_items: 
      - realmd 
      - libnss-sss
      - libpam-sss
      - sssd
      - sssd-tools
      - adcli
      - samba-common-bin
      - oddjob
      - oddjob-mkhomedir
      - packagekit  

    
  - name: test
    become: true
    ansible.builtin.expect: 
      command: "realm join -U hpdp-ad.mgr corp.zim.com"
      responses:
        (?i)password: "S@nktPeterburg!"
    
  

  


  