 - name: install wget 
   package: 
     name: wget 
     state: installed
 
 
 - name: group add
   group:
     name: tomcat
     state: present


 - name: Add the user
   user:
     name: tomcat
     shell: /bin/bash
     groups: tomcat

 - name: Creates directory
   file:
     path: /opt/tomcat
     state: directory
     owner: root
     group: tomcat
     mode: 0775
 
 
 - name: download and unzip unurchive tomcat 8
   unarchive:
     src: http://apache.spd.co.il/tomcat/tomcat-8/v8.5.46/bin/apache-tomcat-8.5.46.tar.gz
     dest: /opt/tomcat
     remote_src: yes 

 - name: Ansible create new file with permissions example.
   file:
     path: /etc/systemd/system/tomcat.service
     state: touch
     mode: 0664
     group: tomcat
     owner: root
  
 - name: create symbolic link latest which will point to the Tomcat installation
   command: ln -s /opt/tomcat/apache-tomcat-8.5.37 /opt/tomcat/latest

 - name: change directory ownership
   command: " chown -R tomcat: /opt/tomcat ""

 - name: Make the scripts inside bin directory executable
   command: sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
 
 - name: create tomcat.service conf file
   blockinfile:
     path: /etc/systemd/system/tomcat.service
     block: |
                [Unit]
                Description=Apache Tomcat Web Application Container
                After=syslog.target network.target

                 [Service]
                 Type=forking

                 Environment=JAVA_HOME=/usr/lib/jvm/jre
                 Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
                 Environment=CATALINA_HOME=/opt/tomcat  
                 Environment=CATALINA_BASE=/opt/tomcat
                 Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
                 Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

                 ExecStart=/opt/tomcat/bin/startup.sh
                 ExecStop=/bin/kill -15 $MAINPID

                 User=tomcat
                 Group=tomcat
                 UMask=0007
                 RestartSec=10
                 Restart=always

                 [Install]
                 WantedBy=multi-user.target  
 