- name: copy template
  copy:
    src: /etc/ansible/roles/zabbix/create.sql.gz
    dest: /root/create.sql.gz 
    
- name: gunzip the file 
  shell: gunzip /root/create.sql.gz 


- name: Restore database
  mysql_db:
    name: zabbix
    state: import
    target: /root/create.sql

- name: Transfer the script
  copy: src=/etc/ansible/roles/zabbix/php.ini dest=/etc/php.ini mode=0600


- name: restart apache 
  service:
     name: httpd
     state: restarted
