- name: add zabbix repo
  command: yum install -y https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm

- name: install zabbix 4 server mysql
  package:
    name: zabbix-server-mysql
    state: installed  

- name: install zabbix 4 web mysql
  package:
    name: zabbix-web-mysql
    state: installed  

- name: install zabbix 4 agent 
  package:
    name: zabbix-agent
    state: installed  

- name: install zabbix 4 get
  package:
    name: zabbix-get
    state: installed 

- name: Import initial schema and data for the server with MySQL
  command: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p Leon21013@